apiVersion: apps/v1 
kind: Deployment 
metadata: 
    name: movie-app
    namespace: default
spec:
  replicas: 4
  selector: 
    MatchLabels:
       app: movie-app
  template:
    metadata:
      labels:
        app: movie-app
    spec:
      containers:
        - name: myc1
          image: lingaraj8747/multibranch-flask-app:build-13
          ports:
            - containerPort: 5000
